

/*
--SELECT * FROM [QuotingV2_UOMs]
DELETE FROM [QuotingV2_UOMs];
DBCC CHECKIDENT ('[QuotingV2_UOMs]', RESEED, 1);
INSERT INTO [QuotingV2_UOMs]([Name],[Description],[DateAdded],[AddedBy]) VALUES('Weight','Total Weight (LB)',GetDate(),'SYSTEM');
INSERT INTO [QuotingV2_UOMs]([Name],[Description],[DateAdded],[AddedBy]) VALUES('Volume','Total Volume (CuFT)',GetDate(),'SYSTEM');
INSERT INTO [QuotingV2_UOMs]([Name],[Description],[DateAdded],[AddedBy]) VALUES('Volume (45LB)','Total Volume (CuFT w/45LB Rule)',GetDate(),'SYSTEM');
INSERT INTO [QuotingV2_UOMs]([Name],[Description],[DateAdded],[AddedBy]) VALUES('Units','Unit Count',GetDate(),'SYSTEM');
INSERT INTO [QuotingV2_UOMs]([Name],[Description],[DateAdded],[AddedBy]) VALUES('Units (Oversize)','Oversized Unit Count',GetDate(),'SYSTEM');

DELETE FROM [QuotingV2_FeeTypes];
DBCC CHECKIDENT ('[QuotingV2_FeeTypes]', RESEED, 1);
INSERT INTO [QuotingV2_FeeTypes]([Name],[Description],[ParentFeeTypeID],[DateAdded],[AddedBy])
VALUES('Ocean', 'Ocean Rates', NULL, GETDATE(), 'SYSTEM');
INSERT INTO [QuotingV2_FeeTypes]([Name],[Description],[ParentFeeTypeID],[DateAdded],[AddedBy])
VALUES('Ocean Base', 'Base Rate for Ocean', SCOPE_IDENTITY(), GETDATE(), 'SYSTEM');

DELETE FROM [QuotingV2_Countries];
DBCC CHECKIDENT ('[QuotingV2_Countries]', RESEED, 1);
INSERT INTO [QuotingV2_Countries]([ShortCode],[LongCode],[Name],[DateAdded],[AddedBy])
VALUES('US','USA','United States of America',GETDATE(),'SYSTEM');

DELETE FROM [QuotingV2_States];
DBCC CHECKIDENT ('[QuotingV2_States]', RESEED, 1);
INSERT INTO [QuotingV2_States]([Code],[Name],[CountryID],[DateAdded],[AddedBy])
VALUES('HI','Hawaii',1,GETDATE(),'SYSTEM');
INSERT INTO [QuotingV2_States]([Code],[Name],[CountryID],[DateAdded],[AddedBy])
VALUES('AK','Alaska',1,GETDATE(),'SYSTEM');

DELETE FROM [QuotingV2_Islands];
DBCC CHECKIDENT ('[QuotingV2_Islands]', RESEED, 1);
INSERT INTO [QuotingV2_Islands]([StateID],[Name],[DateAdded],[AddedBy])
VALUES(1,'Hawaii',GETDATE(),'SYSTEM');
INSERT INTO [QuotingV2_Islands]([StateID],[Name],[DateAdded],[AddedBy])
VALUES(1,'Linai',GETDATE(),'SYSTEM');
INSERT INTO [QuotingV2_Islands]([StateID],[Name],[DateAdded],[AddedBy])
VALUES(1,'Molokai',GETDATE(),'SYSTEM');
INSERT INTO [QuotingV2_Islands]([StateID],[Name],[DateAdded],[AddedBy])
VALUES(1,'Oahu',GETDATE(),'SYSTEM');
INSERT INTO [QuotingV2_Islands]([StateID],[Name],[DateAdded],[AddedBy])
VALUES(1,'Maui',GETDATE(),'SYSTEM');
INSERT INTO [QuotingV2_Islands]([StateID],[Name],[DateAdded],[AddedBy])
VALUES(1,'Kauai',GETDATE(),'SYSTEM');

DELETE FROM [QuotingTool].[dbo].[QuotingV2_Fees];
DBCC CHECKIDENT ('[QuotingV2_Fees]', RESEED, 1);
INSERT INTO [QuotingV2_Fees]([FeeTypeID],[StateID],[IslandID],[Value],[DateAdded],[AddedBy])
VALUES(2, 1, NULL, 6.13, GETDATE(), 'SYSTEM');
INSERT INTO [QuotingV2_Fees]([FeeTypeID],[StateID],[IslandID],[Value],[DateAdded],[AddedBy])
VALUES(2, 1, 2, 2, GETDATE(), 'SYSTEM');
INSERT INTO [QuotingV2_Fees]([FeeTypeID],[StateID],[IslandID],[Value],[DateAdded],[AddedBy])
VALUES(2, 1, 3, 2, GETDATE(), 'SYSTEM');

DELETE FROM [QuotingV2_Cities];
DBCC CHECKIDENT ('[QuotingV2_Cities]', RESEED, 1);
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Island'),'City', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Ahualoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Ahuimano', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Ahukini', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Aiea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Aina Haina', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Akaka Falls', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Ala Moana', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Anaehoomalu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Anahola', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Barbers Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Barking Sands', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Bellows AF Station', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Camp HM Smith', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Camp Maluhia ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Campbell Industrial Park', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Captain Cook', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Chaminade College', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Dowsett Highlands', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Eleele ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Ewa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Ewa Beach', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Fern Acres', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Ford Island NAS', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Fort Derussy Military Reservation', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Fort Kamehameha', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Fort Ruger Military Reservation', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Fort Shafter', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Glennwood', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Haena', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Haiku', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Haina', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hakalau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Halaula', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Halawa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Halawa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Haleakala Park ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Haleiwa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hale Pohaku', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Haliimaile', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Hamakuapoko', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Hamoa ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Hana', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Hanalei', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Hanamaulu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Hanapepe', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Haou', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Happy Valley', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Hauula', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hawaii Beaches', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Hawaii Kai', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Hawaii Natl Guard Diamond Head', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hawaii National Park', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Hawaii National Park', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hawaiian Acres', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hawi', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Heeia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Heeia Kea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Hickman AFB', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hilea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hilo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hoea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Holualoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Holupoe Bay', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Honaunau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Honohina', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Honokaa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honokai Hale', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Honokohau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Honokohau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Honokohau Bay', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Honokohau Harbor', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Honokowai', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Honokua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Honolua Bay', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honolulu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Honopu Bay', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Honouliuli', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Honuapo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Hookena', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Molokai'),'Hoolehua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Huehue', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Huelo ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Humuula', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Iao Valley', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Iwilei', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Joint Base Pearl Harbor', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kaaawa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kaalaea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaalualu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kaanapali', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaapahu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaapahu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaauhuhu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Kaena Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kaena Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kahakuloa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kahala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kahaluu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kahaluu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kahana', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kahana', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kahe Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kahei', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kahikinui Forest Reserve', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kahua Ranch', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kahuku', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kahuku Ranch', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kahului', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kai Malino', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaiaakea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kailua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kailua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kailua Kona', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kaimuki', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kainaliu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Kaiolohia Bay', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaiwiki', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kakuiula', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kalae', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kalaheo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kalama', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kalama Park', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kalaoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kalaoa Camp', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kalapana', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Molokai'),'Kalaupapa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kalepolepo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kalihi', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kalihi Kai', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kalihiwai', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kalopa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Kamaiki Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kamaili', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kamoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kamooloa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kamuela', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kaneilio Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kaneohe', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kaneohe MCAS', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kapaa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kapaau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kapahee', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kapahulu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kapai ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kapala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kapalama', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kapalua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kapapala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kapehu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kapoho', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kapolei', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kapulena', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaueleau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kaumakani', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Kaumalapau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Kaumalapau Harbor', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaumana', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Molokai'),'Kaunakakai', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Kaunolu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kaupakalua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kaupo ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kaupulehu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kawaihae', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kawaihua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kawailoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kawainui', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kawela', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kawela', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Keahole Airport', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Keaiwa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kealakekua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kealia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kealia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kealia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Keanae', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Keanapapa Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Keauhou', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Keaukaha', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Keawekapu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Keaau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Keei', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kehena', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kekaha', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Keokea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Keokea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Keomuku', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kihalani', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kihei', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Kikoa Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kilauea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kilauea Military Camp', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kiolakaa Keaa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kipahulu Forest Reserve', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kipu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Koae', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Koali', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kohala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Kokee', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Koko Head', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kokomo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kolo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Koloa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Molokai'),'Kualapuu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kualoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kuau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kuhio Village', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kuiaha', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kukaiau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kukuihaele', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Kula', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kulani Prison', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kuliouou ', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Kunia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Kurtistown', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Lahaina', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Laie', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Lalamilo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Lanai Airport', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Lanai City', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Lanikai', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Lonoulu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Launiupoko', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Laupahoehoe', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Lawai', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Libbyville', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Lihue', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Lower Paia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Lualualei', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Lydgate park', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Maalaea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Mahinui', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Mahukona', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Maili', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Makaalae', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Makaha', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Makakilo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Makapala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Makapuu Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Makawao', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Makaweli', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Makena', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Makua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Mala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Malae', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Maliko', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Mana', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Manele Bay', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Manoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Maulua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Mauna Kea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Mauna Loa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Molokai'),'Maunaloa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Manunawili', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Mauula', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Mcgrew Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Mikilua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Miliani', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Milolii', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Moanalua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Moanalua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Moilili', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Mokapu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Mokuleia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Moloaa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Mountain View', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Muolea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Naalehu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Nahiku', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Naanakuli', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Napili', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Napoopoo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Naval Air Station', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Nawiliwili', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'New Mill', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Ninole', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Niu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Niulii', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Niumalu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Numila', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Nuuanu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Ocean View', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Okoe', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Olaa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Olinda', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Olowalu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Omaopia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Onomea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Ookala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Opihikao', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Paauhau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Paauilo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Pahala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Pahoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Pahoehoe', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Paia', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Pakala', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Paloa Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Palolo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Panaewa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Papa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Papaaloa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Papaikou', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Paukaa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Paukukalo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Paumalu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Pauwela', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Pawaa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Peahi', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Pearl City', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Pearl Harbor', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Pepeekeo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Piihonua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Pohakea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Pohakuloa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Lanai'),'Pohakuloa Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Pohoiki', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Pohoiki', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Poipu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Pomoho', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Port Allen', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Portlock', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Princeville', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Puako', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Puhi', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Pukalani', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Pulehua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Punaluu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Punaluu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Pupukea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Puu Heu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Puu Waa Waa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Puuanahulu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Puueo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Puuiki', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Puukolii', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Puunene', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Saint Louis Heights', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Sand Island', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Schofield Barracks', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Shipman Industrial', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'South Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Spreckelsville', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Sunset Beach', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Tantalus', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Tripler Amc', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Ulumalu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Ulupalakua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Umikoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii '),'Union Mill', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'University of Hawaii', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Upolu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Upolu Point', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Volcano', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Volcano House', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Volcano National Park', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Wahiawa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Wahiawa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waiahole', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Waiakea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Waiakoa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waialae', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waialua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waianae', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waiau', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Walehu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Waihee', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waikane', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Waikapu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waikele', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Waikii', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waikiki', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Waikoloa', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Wailea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Wailea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Wailua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Wailua', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Wailuku', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waimalu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waimanalo', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Waimea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Waimea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waimea', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waimea Camp', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Wainaku', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Wainee', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Kauai'),'Wainiha', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Waiohinu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Maui'),'Waiohuli', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waipahu', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Waipio', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waipio', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Waipio Acres', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Waipio Valley', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Hawaii'),'Waipunalei', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Wake Island', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'West Loch', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Wheeler AFB', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Wheeler Army', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Whitmore Village', GetDate(), 'SYSTEM');
INSERT INTO QuotingV2_Cities(StateID,IslandID,Name,[DateAdded],[AddedBy]) VALUEs(1,(SELECT IslandID FROM QuotingV2_Islands WHERE Name='Oahu'),'Wihelmina Rise', GetDate(), 'SYSTEM');
*/


GO
