//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AJC.Logistics.SeaWideExpress.QuotingTool.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuotingToolRepository : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuotingToolRepository object using the connection string found in the 'QuotingToolRepository' section of the application configuration file.
        /// </summary>
        public QuotingToolRepository() : base("name=QuotingToolRepository", "QuotingToolRepository")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuotingToolRepository object.
        /// </summary>
        public QuotingToolRepository(string connectionString) : base(connectionString, "QuotingToolRepository")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuotingToolRepository object.
        /// </summary>
        public QuotingToolRepository(EntityConnection connection) : base(connection, "QuotingToolRepository")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Test> Test
        {
            get
            {
                if ((_Test == null))
                {
                    _Test = base.CreateObjectSet<Test>("Test");
                }
                return _Test;
            }
        }
        private ObjectSet<Test> _Test;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Test EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTest(Test test)
        {
            base.AddObject("Test", test);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuotingToolModel", Name="Test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Test object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Test CreateTest(global::System.Int32 id)
        {
            Test test = new Test();
            test.id = id;
            return test;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechadesde
        {
            get
            {
                return _fechadesde;
            }
            set
            {
                OnfechadesdeChanging(value);
                ReportPropertyChanging("fechadesde");
                _fechadesde = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechadesde");
                OnfechadesdeChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechadesde;
        partial void OnfechadesdeChanging(Nullable<global::System.DateTime> value);
        partial void OnfechadesdeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechahasta
        {
            get
            {
                return _fechahasta;
            }
            set
            {
                OnfechahastaChanging(value);
                ReportPropertyChanging("fechahasta");
                _fechahasta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechahasta");
                OnfechahastaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechahasta;
        partial void OnfechahastaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechahastaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> zona
        {
            get
            {
                return _zona;
            }
            set
            {
                OnzonaChanging(value);
                ReportPropertyChanging("zona");
                _zona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zona");
                OnzonaChanged();
            }
        }
        private Nullable<global::System.Int32> _zona;
        partial void OnzonaChanging(Nullable<global::System.Int32> value);
        partial void OnzonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zonaDescripcion
        {
            get
            {
                return _zonaDescripcion;
            }
            set
            {
                OnzonaDescripcionChanging(value);
                ReportPropertyChanging("zonaDescripcion");
                _zonaDescripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("zonaDescripcion");
                OnzonaDescripcionChanged();
            }
        }
        private global::System.String _zonaDescripcion;
        partial void OnzonaDescripcionChanging(global::System.String value);
        partial void OnzonaDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private Nullable<global::System.Decimal> _precio;
        partial void OnprecioChanging(Nullable<global::System.Decimal> value);
        partial void OnprecioChanged();

        #endregion

    
    }

    #endregion

    
}
